#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 15 22:01:41 2020

@author: aimldl
"""

#print("hello, world")
#p = int( input() )
#print( p )

number = 100000

count_max = 10
count = 0
for divisor in range(1, number+1):
    quotient = number % divisor
    if quotient == 0:
        print( divisor, end='' )
        count += 1
        if count % count_max ==0:
          print('')
        else:
          print( end=' ')